fix: Use existing client if one is running
ipfs-shipyard/pinning-service-compliance pull request #28
Opened 2022-04-25 20:44 UTC by SgtPooki

fixes #25

2022-04-26 16:41 UTC, lidel requested changes
- Inline CIDs creation can be done in pure JS – see comment inline
- Avoid reusing daemon if present – tests should use a clean, controlled instance (especially when we will use it for bitswap / DHT tests)

2022-04-26 16:41 UTC, lidel commented on src/utils/getIpfsClient.ts
> +  }
We should not use default daemon/port in tests, these tests were always a headache to maintain and debug because of unexpected side-effects.

Other test suites like sharness in go-ipfs or https://github.com/ipfs/interop  use ephemeral node spawned on random ports.

```suggestion
```

2022-04-26 16:41 UTC, lidel commented on src/utils/getIpfsClient.ts
> +    })
Tests should always spawn a clean, `disposable` and `test` instance.

See https://github.com/ipfs-shipyard/pinning-service-compliance/issues/25#issuecomment-1108838708

2022-04-26 17:58 UTC, SgtPooki commented on src/utils/getIpfsClient.ts
> +  }
Can you link me to an example for creating an ephemeral daemon?

2022-04-27 12:12 UTC, achingbrain requested changes

2022-04-27 12:12 UTC, achingbrain commented on CHANGELOG.md
> +## [0.0.3](https://github.com/ipfs-shipyard/pinning-service-compliance/compare/v0.0.2...v0.0.3) (2022-04-25)
Was this change intentional?

2022-04-27 12:12 UTC, achingbrain commented on package.json
> +  "version": "0.0.3",
Was this change intentional?

2022-04-27 12:12 UTC, achingbrain commented on src/utils/getInlineCid.ts
> +    logger.error('Could not get an ipfs client', err)
The double-catch here means if `CID.createV1` throws, you'll get `'Problem creating an inline CID'` and then `'Could not get an ipfs client'` as well in the logs.  Might be clearer to remove the nesting and just have one error log line for one error?

2022-04-27 12:12 UTC, achingbrain commented on src/utils/getIpfsClient.ts
> +import { join } from 'path'
Is the export from this file used anywhere or can the whole thing be removed?

2022-04-27 12:12 UTC, achingbrain commented on tsconfig.json
> +    "types": ["@ipfs-shipyard/pinning-service-client", "node", "multiformats"],
This adds the `multiformats` types [to the global scope](https://www.typescriptlang.org/tsconfig#types), do we want that?

2022-04-28 06:44 UTC, SgtPooki commented on CHANGELOG.md
> +## [0.0.3](https://github.com/ipfs-shipyard/pinning-service-compliance/compare/v0.0.2...v0.0.3) (2022-04-25)
kind of. this was made my aegir when doing an npm release in order to test running the compliance checker from npm. Obviously, those are just testing releases, but I didn't think doing release candidates pre-v1 for a newly launched tool was necessary. Feel free to educate me :)

2022-04-28 06:45 UTC, SgtPooki commented on src/utils/getInlineCid.ts
> +    logger.error('Could not get an ipfs client', err)
absolutely.

2022-04-28 06:47 UTC, SgtPooki commented on src/utils/getIpfsClient.ts
> +import { join } from 'path'
this will be used in the future for other compliance checks. It's not currently being used though, since we switched to using multiformats for inlineCID creation

2022-04-28 07:03 UTC, SgtPooki commented on tsconfig.json
> +    "types": ["@ipfs-shipyard/pinning-service-client", "node", "multiformats"],
nope! thanks.

2022-04-28 07:03 UTC, SgtPooki commented on src/utils/getInlineCid.ts
> +    logger.error('Could not get an ipfs client', err)
https://github.com/ipfs-shipyard/pinning-service-compliance/pull/28/commits/23c71997b491bcf5f822a1c5fc55c55e68b04cb8

2022-04-28 07:04 UTC, SgtPooki commented on package.json
> +  "version": "0.0.3",
this was done to test npx usage was still working correctly. If there is a better recommended practice I should be following for this situation, please let me know

2022-05-05 15:25 UTC, SgtPooki reviewed
No review for a while, I'm going to merge and we can discuss later if necessary.

2022-05-05 15:25 UTC, merged